//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginPractica2_5to.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PL_PracticaEntities1 : DbContext
    {
        public PL_PracticaEntities1()
            : base("name=PL_PracticaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_DEPARTAMENTO> TBL_DEPARTAMENTO { get; set; }
        public virtual DbSet<TBL_ESTADO> TBL_ESTADO { get; set; }
        public virtual DbSet<TBL_INCIDENTE> TBL_INCIDENTE { get; set; }
        public virtual DbSet<TBL_OBSERVACION> TBL_OBSERVACION { get; set; }
        public virtual DbSet<TBL_PERSONA> TBL_PERSONA { get; set; }
        public virtual DbSet<TBL_PRIORIDAD> TBL_PRIORIDAD { get; set; }
        public virtual DbSet<TBL_ROL> TBL_ROL { get; set; }
        public virtual DbSet<TBL_USUARIO> TBL_USUARIO { get; set; }
    
        public virtual ObjectResult<string> Sp_Correo(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Sp_Correo", usuarioParameter);
        }
    
        public virtual ObjectResult<TBL_USUARIO> Obtener_Claves(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_USUARIO>("Obtener_Claves", usuarioParameter);
        }
    
        public virtual ObjectResult<TBL_USUARIO> Obtener_Claves(string usuario, MergeOption mergeOption)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_USUARIO>("Obtener_Claves", mergeOption, usuarioParameter);
        }
    }
}
