//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginPractica2_5to.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INCIDENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_INCIDENTE()
        {
            this.TBL_OBSERVACION = new HashSet<TBL_OBSERVACION>();
            this.TBL_OBSERVACION1 = new HashSet<TBL_OBSERVACION>();
        }
    
        public int inc_id { get; set; }
        public System.DateTime inc_fecha { get; set; }
        public System.DateTime inc_vigencia { get; set; }
        public string inc_numticket { get; set; }
        public string inc_comentario { get; set; }
        public string inc_tipo { get; set; }
        public string inc_status { get; set; }
        public System.DateTime inc_add { get; set; }
        public int per_id { get; set; }
        public int est_id { get; set; }
        public int pri_id { get; set; }
    
        public virtual TBL_ESTADO TBL_ESTADO { get; set; }
        public virtual TBL_PERSONA TBL_PERSONA { get; set; }
        public virtual TBL_PRIORIDAD TBL_PRIORIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_OBSERVACION> TBL_OBSERVACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_OBSERVACION> TBL_OBSERVACION1 { get; set; }
    }
}
